package com.jasonwu.firenfcreader;
import android.app.*; import android.os.*; import android.hardware.usb.*; import android.content.*; import android.graphics.Typeface; import android.view.*; import android.widget.*;
import com.hoho.android.usbserial.driver.*; import java.util.*;
public class MainActivity extends Activity {
 static final String ACT="com.jasonwu.firenfcreader.USB_PERMISSION"; TextView status,uid,diag; UsbSerialPort port; UsbManager mgr; Handler ui=new Handler(Looper.getMainLooper()); final Object lock=new Object();
 static final byte[] WAKE={(byte)0x55,(byte)0x55,0,0,0}, FW={0,0,(byte)0xff,2,(byte)0xfe,(byte)0xd4,0x02,0x2a,0}, SAM={0,0,(byte)0xff,5,(byte)0xfb,(byte)0xd4,0x14,0x01,0x14,0x01,0x02,0}, POLL={0,0,(byte)0xff,4,(byte)0xfc,(byte)0xd4,0x4a,0x01,0x00,(byte)0xe1,0};
 BroadcastReceiver rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(ACT.equals(i.getAction())){UsbDevice d=i.getParcelableExtra(UsbManager.EXTRA_DEVICE);if(i.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED,false)&&d!=null)connect(d);else msg("USB permission denied");}}};
 public void onCreate(Bundle b){super.onCreate(b);ScrollView sv=new ScrollView(this);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(30,45,30,30);sv.addView(x);TextView t=new TextView(this);t.setText("Fire NFC Reader — v1.3 Recovery");t.setTextSize(24);t.setTypeface(null,Typeface.BOLD);status=new TextView(this);status.setTextSize(18);status.setPadding(0,25,0,12);uid=new TextView(this);uid.setTextSize(20);uid.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);diag=new TextView(this);diag.setTextSize(13);diag.setTypeface(Typeface.MONOSPACE,Typeface.NORMAL);diag.setTextIsSelectable(true);diag.setPadding(0,18,0,18);x.addView(t);x.addView(status);x.addView(uid);x.addView(diag);
  add(x,"Automatic Recovery",v->recover());add(x,"Reconnect USB",v->find());add(x,"Get Firmware",v->command("GET FIRMWARE",FW,800));add(x,"Initialize (SAM)",v->command("SAM CONFIG",SAM,800));add(x,"Poll Once",v->command("POLL",POLL,1000));setContentView(sv);mgr=(UsbManager)getSystemService(USB_SERVICE);IntentFilter f=new IntentFilter(ACT);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);find();}
 void add(LinearLayout x,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);x.addView(b);}
 void find(){try{if(port!=null)port.close();}catch(Exception e){}port=null;uid.setText("");msg("STATE: SEARCHING USB");dmsg("Searching...");List<UsbSerialDriver>d=UsbSerialProber.getDefaultProber().findAllDrivers(mgr);if(d.isEmpty()){msg("STATE: NO USB DEVICE");return;}UsbDevice u=d.get(0).getDevice();dmsg("USB FOUND\nVID:PID "+String.format(Locale.US,"%04X:%04X",u.getVendorId(),u.getProductId())+"\nPermission: "+mgr.hasPermission(u));if(!mgr.hasPermission(u)){msg("STATE: WAITING FOR USB PERMISSION");mgr.requestPermission(u,PendingIntent.getBroadcast(this,0,new Intent(ACT),Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0));}else connect(u);}
 void connect(UsbDevice d){try{UsbSerialDriver q=null;for(UsbSerialDriver z:UsbSerialProber.getDefaultProber().findAllDrivers(mgr))if(z.getDevice().getDeviceId()==d.getDeviceId())q=z;if(q==null)throw new Exception("serial driver not found");port=q.getPorts().get(0);port.open(mgr.openDevice(d));port.setParameters(115200,8,UsbSerialPort.STOPBITS_1,UsbSerialPort.PARITY_NONE);try{port.setDTR(false);port.setRTS(false);}catch(Exception ignored){}msg("STATE: USB SERIAL OPEN");dmsg("Serial OPEN @ 115200 8N1\nDTR=false RTS=false\nTap AUTOMATIC RECOVERY.");}catch(Exception e){msg("STATE: USB CONNECTION ERROR");dmsg(e.toString());}}
 void recover(){if(port==null){msg("STATE: SERIAL NOT OPEN");return;}new Thread(()->{synchronized(lock){StringBuilder log=new StringBuilder("PN532 RECOVERY LOG\n");try{msg("STATE: RECOVERY RUNNING");Thread.sleep(700);boolean[][] lines={{false,false},{true,false},{false,true},{true,true}};int attempt=0;for(boolean[]lr:lines){try{port.setDTR(lr[0]);port.setRTS(lr[1]);}catch(Exception e){log.append("Control lines unsupported: ").append(e.getMessage()).append("\n");}Thread.sleep(200);for(int k=0;k<2;k++){attempt++;drain();port.write(WAKE,1000);Thread.sleep(180);byte[]wr=read(180);drain();port.write(FW,1000);byte[]fr=read(900);log.append("\n#").append(attempt).append(" DTR=").append(lr[0]).append(" RTS=").append(lr[1]).append("\nWake RX: ").append(hex(wr)).append("\nFW RX: ").append(hex(fr)).append("\n");dmsg(log.toString());if(contains(fr,0xd5,0x03)){log.append("✓ PN532 FOUND\n");dmsg(log.toString());msg("STATE: PN532 FOUND — INITIALIZING");drain();port.write(SAM,1000);byte[]sr=read(800);log.append("SAM RX: ").append(hex(sr)).append("\n");dmsg(log.toString());msg(contains(sr,0xd5,0x15)?"STATE: PN532 READY — TRY POLL ONCE":"STATE: FIRMWARE OK, SAM RESPONSE UNCLEAR");return;}Thread.sleep(250);}}msg("STATE: RECOVERY FINISHED — NO PN532 RESPONSE");log.append("\nNo D5 03 firmware response in ").append(attempt).append(" attempts.");dmsg(log.toString());}catch(Exception e){msg("STATE: RECOVERY ERROR");log.append("\nERROR: ").append(e);dmsg(log.toString());}}}).start();}
 void command(String name,byte[]tx,int wait){if(port==null){msg("STATE: SERIAL NOT OPEN");return;}new Thread(()->{synchronized(lock){try{drain();port.write(tx,1000);byte[]a=read(wait);String id=parse(a);if(id!=null){String s=id;ui.post(()->uid.setText("UID: "+s));}msg("STATE: "+name+(a.length>0?" — RX RECEIVED":" — NO RESPONSE"));dmsg("COMMAND: "+name+"\nTX: "+hex(tx)+"\nRX: "+hex(a)+(id!=null?"\n✓ TAG UID: "+id:""));}catch(Exception e){msg("STATE: "+name+" ERROR");dmsg(e.toString());}}}).start();}
 byte[] read(int wait)throws Exception{long end=System.currentTimeMillis()+wait;java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();byte[]b=new byte[256];while(System.currentTimeMillis()<end){int n=port.read(b,60);if(n>0)o.write(b,0,n);}return o.toByteArray();}
 void drain(){try{byte[]b=new byte[256];while(port.read(b,20)>0){}}catch(Exception e){}}
 boolean contains(byte[]a,int x,int y){for(int i=0;i+1<a.length;i++)if((a[i]&255)==x&&(a[i+1]&255)==y)return true;return false;}String hex(byte[]a){if(a==null||a.length==0)return "(none)";StringBuilder s=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)s.append(' ');s.append(String.format(Locale.US,"%02X",a[i]&255));}return s.toString();}
 String parse(byte[]a){for(int i=0;i+10<a.length;i++)if((a[i]&255)==0xd5&&(a[i+1]&255)==0x4b&&(a[i+2]&255)>=1){int p=i+3;p++;p+=2;p++;if(p>=a.length)continue;int n=a[p++]&255;if(n<4||n>10||p+n>a.length)continue;StringBuilder s=new StringBuilder();for(int k=0;k<n;k++){if(k>0)s.append(':');s.append(String.format(Locale.US,"%02X",a[p+k]&255));}return s.toString();}return null;}
 void msg(String s){ui.post(()->status.setText(s));}void dmsg(String s){ui.post(()->diag.setText(s));}protected void onDestroy(){try{if(port!=null)port.close();}catch(Exception e){}unregisterReceiver(rx);super.onDestroy();}
}