package com.jasonwu.firenfcreader;
import android.app.*; import android.os.*; import android.hardware.usb.*; import android.content.*; import android.graphics.Typeface; import android.view.*; import android.widget.*;
import com.hoho.android.usbserial.driver.*; import java.util.*;
public class MainActivity extends Activity {
 static final String ACT="com.jasonwu.firenfcreader.USB_PERMISSION"; TextView status,uid,diag; UsbSerialPort port; UsbManager mgr; Handler ui=new Handler(Looper.getMainLooper()); final Object lock=new Object();
 static final byte[] WAKE={(byte)0x55,(byte)0x55,0,0,0};
 static final byte[] FW={0,0,(byte)0xff,2,(byte)0xfe,(byte)0xd4,0x02,0x2a,0};
 static final byte[] SAM={0,0,(byte)0xff,5,(byte)0xfb,(byte)0xd4,0x14,0x01,0x14,0x01,0x02,0};
 static final byte[] POLL={0,0,(byte)0xff,4,(byte)0xfc,(byte)0xd4,0x4a,0x01,0x00,(byte)0xe1,0};
 BroadcastReceiver rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(ACT.equals(i.getAction())){UsbDevice d=i.getParcelableExtra(UsbManager.EXTRA_DEVICE);if(i.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED,false)&&d!=null)connect(d);else msg("USB permission denied");}}};
 public void onCreate(Bundle b){super.onCreate(b); ScrollView sv=new ScrollView(this);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(30,45,30,30);sv.addView(x);
  TextView t=new TextView(this);t.setText("Fire NFC Reader — v1.2 Diagnostics");t.setTextSize(24);t.setTypeface(null,Typeface.BOLD);status=new TextView(this);status.setTextSize(18);status.setPadding(0,25,0,12);uid=new TextView(this);uid.setTextSize(20);uid.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);
  diag=new TextView(this);diag.setTextSize(13);diag.setTypeface(Typeface.MONOSPACE,Typeface.NORMAL);diag.setTextIsSelectable(true);diag.setPadding(0,18,0,18);
  x.addView(t);x.addView(status);x.addView(uid);x.addView(diag);
  String[] names={"Reconnect USB","Send Wake","Get Firmware","Initialize (SAM)","Poll Once"};
  for(String n:names){Button z=new Button(this);z.setText(n);if(n.startsWith("Reconnect"))z.setOnClickListener(v->find());else if(n.startsWith("Send"))z.setOnClickListener(v->command("WAKE",WAKE,400));else if(n.startsWith("Get"))z.setOnClickListener(v->command("GET FIRMWARE",FW,700));else if(n.startsWith("Initialize"))z.setOnClickListener(v->command("SAM CONFIG",SAM,700));else z.setOnClickListener(v->command("POLL",POLL,1000));x.addView(z);}setContentView(sv);mgr=(UsbManager)getSystemService(USB_SERVICE);
  IntentFilter f=new IntentFilter(ACT);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);find();}
 void find(){try{if(port!=null)port.close();}catch(Exception e){}port=null;uid.setText("");msg("STATE: SEARCHING USB");dmsg("Searching...");
  List<UsbSerialDriver>d=UsbSerialProber.getDefaultProber().findAllDrivers(mgr);if(d.isEmpty()){msg("STATE: NO USB DEVICE");dmsg("No supported USB serial device.");return;}UsbDevice u=d.get(0).getDevice();dmsg("USB FOUND\nVID:PID "+String.format(Locale.US,"%04X:%04X",u.getVendorId(),u.getProductId())+"\nDevice: "+u.getDeviceName()+"\nPermission: "+mgr.hasPermission(u));if(!mgr.hasPermission(u)){msg("STATE: WAITING FOR USB PERMISSION");PendingIntent p=PendingIntent.getBroadcast(this,0,new Intent(ACT),Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0);mgr.requestPermission(u,p);}else connect(u);}
 void connect(UsbDevice d){try{UsbSerialDriver q=null;for(UsbSerialDriver z:UsbSerialProber.getDefaultProber().findAllDrivers(mgr))if(z.getDevice().getDeviceId()==d.getDeviceId())q=z;if(q==null)throw new Exception("serial driver not found");port=q.getPorts().get(0);port.open(mgr.openDevice(d));port.setParameters(115200,8,UsbSerialPort.STOPBITS_1,UsbSerialPort.PARITY_NONE);msg("STATE: USB SERIAL OPEN");dmsg("USB serial OPEN\n115200 baud, 8N1\n\nUse buttons below in order:\n1. Send Wake\n2. Get Firmware\n3. Initialize (SAM)\n4. Poll Once");}catch(Exception e){msg("STATE: USB CONNECTION ERROR");dmsg(e.toString());}}
 void command(String name,byte[]tx,int wait){if(port==null){msg("STATE: SERIAL NOT OPEN");return;}new Thread(()->{synchronized(lock){try{drain();port.write(tx,1000);byte[]a=read(wait);String extra="";if(name.equals("GET FIRMWARE")&&contains(a,0xd5,0x03))extra="\n✓ PN532 GetFirmwareVersion response detected";if(name.equals("SAM CONFIG")&&contains(a,0xd5,0x15))extra="\n✓ PN532 SAMConfiguration response detected";String id=parse(a);if(id!=null){String s=id;ui.post(()->uid.setText("UID: "+s));extra+="\n✓ TAG UID: "+id;}final String e=extra;msg("STATE: "+name+(a.length>0?" — RX RECEIVED":" — NO RESPONSE"));dmsg("COMMAND: "+name+"\n\nTX ("+tx.length+" bytes):\n"+hex(tx)+"\n\nRX ("+a.length+" bytes):\n"+hex(a)+e);}catch(Exception e){msg("STATE: "+name+" ERROR");dmsg(e.toString());}}}).start();}
 byte[] read(int wait)throws Exception{long end=System.currentTimeMillis()+wait;java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();byte[]b=new byte[256];while(System.currentTimeMillis()<end){int n=port.read(b,60);if(n>0)o.write(b,0,n);}return o.toByteArray();}
 void drain(){try{byte[]b=new byte[256];while(port.read(b,20)>0){}}catch(Exception e){}}
 boolean contains(byte[]a,int x,int y){for(int i=0;i+1<a.length;i++)if((a[i]&255)==x&&(a[i+1]&255)==y)return true;return false;}
 String hex(byte[]a){if(a==null||a.length==0)return "(none)";StringBuilder s=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)s.append(' ');s.append(String.format(Locale.US,"%02X",a[i]&255));}return s.toString();}
 String parse(byte[]a){for(int i=0;i+10<a.length;i++)if((a[i]&255)==0xd5&&(a[i+1]&255)==0x4b&&(a[i+2]&255)>=1){int p=i+3;p++;p+=2;p++;if(p>=a.length)continue;int n=a[p++]&255;if(n<4||n>10||p+n>a.length)continue;StringBuilder s=new StringBuilder();for(int k=0;k<n;k++){if(k>0)s.append(':');s.append(String.format(Locale.US,"%02X",a[p+k]&255));}return s.toString();}return null;}
 void msg(String s){ui.post(()->status.setText(s));}void dmsg(String s){ui.post(()->diag.setText(s));}
 protected void onDestroy(){try{if(port!=null)port.close();}catch(Exception e){}unregisterReceiver(rx);super.onDestroy();}
}