package com.jasonwu.firenfcreader;
import android.app.*; import android.os.*; import android.hardware.usb.*; import android.content.*; import android.graphics.Typeface; import android.view.*; import android.widget.*;
import com.hoho.android.usbserial.driver.*; import java.util.*;
public class MainActivity extends Activity {
 static final String ACT="com.jasonwu.firenfcreader.USB_PERMISSION"; TextView status,uid,diag; UsbSerialPort port; UsbManager mgr; Handler ui=new Handler(Looper.getMainLooper()); final Object lock=new Object();
 static final byte[] PRE={(byte)0x55,(byte)0x55,0,0,0,0,0,0,0,0,0,0,0,0,0,0}, FW={0,0,(byte)0xff,2,(byte)0xfe,(byte)0xd4,0x02,0x2a,0}, SAM={0,0,(byte)0xff,5,(byte)0xfb,(byte)0xd4,0x14,0x01,0x14,0x01,0x02,0}, POLL={0,0,(byte)0xff,4,(byte)0xfc,(byte)0xd4,0x4a,0x01,0x00,(byte)0xe1,0};
 BroadcastReceiver rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(ACT.equals(i.getAction())){UsbDevice d=i.getParcelableExtra(UsbManager.EXTRA_DEVICE);if(i.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED,false)&&d!=null)connect(d);else msg("USB permission denied");}}};
 public void onCreate(Bundle b){super.onCreate(b);ScrollView sv=new ScrollView(this);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(30,45,30,30);sv.addView(x);TextView t=new TextView(this);t.setText("Fire NFC Reader — v1.5 Elechouse Sequence");t.setTextSize(24);t.setTypeface(null,Typeface.BOLD);status=new TextView(this);status.setTextSize(18);status.setPadding(0,25,0,12);uid=new TextView(this);uid.setTextSize(20);uid.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);diag=new TextView(this);diag.setTextSize(13);diag.setTypeface(Typeface.MONOSPACE,Typeface.NORMAL);diag.setTextIsSelectable(true);diag.setPadding(0,18,0,18);x.addView(t);x.addView(status);x.addView(uid);x.addView(diag);add(x,"Read Tag (Elechouse sequence)",v->readTag());add(x,"Reconnect USB",v->find());add(x,"Initialize (SAM)",v->command("SAM CONFIG",SAM,1000));add(x,"Poll Once",v->command("POLL",POLL,1200));setContentView(sv);mgr=(UsbManager)getSystemService(USB_SERVICE);IntentFilter f=new IntentFilter(ACT);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);find();}
 void add(LinearLayout x,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);x.addView(b);}
 void find(){try{if(port!=null)port.close();}catch(Exception e){}port=null;uid.setText("");msg("STATE: SEARCHING USB");List<UsbSerialDriver>d=UsbSerialProber.getDefaultProber().findAllDrivers(mgr);if(d.isEmpty()){msg("STATE: NO USB DEVICE");return;}UsbDevice u=d.get(0).getDevice();dmsg("USB FOUND\nVID:PID "+String.format(Locale.US,"%04X:%04X",u.getVendorId(),u.getProductId())+"\nPermission: "+mgr.hasPermission(u));if(!mgr.hasPermission(u)){msg("STATE: WAITING FOR USB PERMISSION");mgr.requestPermission(u,PendingIntent.getBroadcast(this,0,new Intent(ACT),Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0));}else connect(u);}
 void connect(UsbDevice d){try{UsbSerialDriver q=null;for(UsbSerialDriver z:UsbSerialProber.getDefaultProber().findAllDrivers(mgr))if(z.getDevice().getDeviceId()==d.getDeviceId())q=z;if(q==null)throw new Exception("serial driver not found");port=q.getPorts().get(0);port.open(mgr.openDevice(d));port.setParameters(115200,8,UsbSerialPort.STOPBITS_1,UsbSerialPort.PARITY_NONE);msg("STATE: USB SERIAL OPEN");dmsg("Serial OPEN @ 115200 8N1\n\nTap READ TAG.");}catch(Exception e){msg("STATE: USB CONNECTION ERROR");dmsg(e.toString());}}
 void readTag(){if(port==null){msg("STATE: SERIAL NOT OPEN");return;}new Thread(()->{synchronized(lock){StringBuilder l=new StringBuilder("ELECHOUSE HSU SEQUENCE\\n");try{msg("STATE: READING TAG");byte[] fw=txWake(FW,2400);l.append("FW: ").append(hex(fw)).append("\\n");if(!contains(fw,0xd5,0x03))throw new Exception("No firmware response");byte[] sam=txWake(SAM,2200);l.append("SAM: ").append(hex(sam)).append("\\n");if(!contains(sam,0xd5,0x15))throw new Exception("No SAM response");byte[] rf=frame(0x32,new int[]{0x05,0xff,0x01,0x01});byte[] rr=txPlain(rf,1800);l.append("RF: ").append(hex(rr)).append("\\n");byte[] pr=txPlain(POLL,2200);l.append("POLL: ").append(hex(pr)).append("\\n");String id=parse(pr);if(id!=null){String z=id;ui.post(()->uid.setText("UID: "+z));l.append("TAG UID: ").append(id);msg("STATE: TAG DETECTED");}else msg("STATE: PN532 READY — NO TAG DETECTED");dmsg(l.toString());}catch(Exception e){l.append("ERROR: ").append(e);dmsg(l.toString());msg("STATE: SEQUENCE FAILED");}}}).start();}
 byte[] txWake(byte[]cmd,int wait)throws Exception{byte[]w=new byte[PRE.length+cmd.length];System.arraycopy(PRE,0,w,0,PRE.length);System.arraycopy(cmd,0,w,PRE.length,cmd.length);drain();port.write(w,1500);return read(wait);}
 byte[] txPlain(byte[]cmd,int wait)throws Exception{drain();port.write(cmd,1500);return read(wait);}
 byte[] frame(int command,int[]params){int n=2+params.length;byte[]a=new byte[n+7];a[0]=0;a[1]=0;a[2]=(byte)0xff;a[3]=(byte)n;a[4]=(byte)(256-n);a[5]=(byte)0xd4;a[6]=(byte)command;int sum=0xd4+command;for(int i=0;i<params.length;i++){a[7+i]=(byte)params[i];sum+=params[i];}a[5+n]=(byte)(256-(sum&255));a[6+n]=0;return a;}
 void command(String name,byte[]tx,int wait){if(port==null){msg("STATE: SERIAL NOT OPEN");return;}new Thread(()->{synchronized(lock){try{drain();port.write(tx,1000);byte[]a=read(wait);String id=parse(a);if(id!=null){String s=id;ui.post(()->uid.setText("UID: "+s));}msg("STATE: "+name+(a.length>0?" — RX RECEIVED":" — NO RESPONSE"));dmsg("COMMAND: "+name+"\nTX: "+hex(tx)+"\nRX: "+hex(a)+(id!=null?"\nTAG UID: "+id:""));}catch(Exception e){msg("STATE: "+name+" ERROR");dmsg(e.toString());}}}).start();}
 byte[] read(int wait)throws Exception{long end=System.currentTimeMillis()+wait;java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();byte[]b=new byte[256];while(System.currentTimeMillis()<end){int n=port.read(b,80);if(n>0)o.write(b,0,n);}return o.toByteArray();}void drain(){try{byte[]b=new byte[256];while(port.read(b,20)>0){}}catch(Exception e){}}
 boolean contains(byte[]a,int x,int y){for(int i=0;i+1<a.length;i++)if((a[i]&255)==x&&(a[i+1]&255)==y)return true;return false;}boolean containsSeq(byte[]a,int[]q){outer:for(int i=0;i+q.length<=a.length;i++){for(int j=0;j<q.length;j++)if((a[i+j]&255)!=q[j])continue outer;return true;}return false;}String hex(byte[]a){if(a==null||a.length==0)return "(none)";StringBuilder s=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)s.append(' ');s.append(String.format(Locale.US,"%02X",a[i]&255));}return s.toString();}
 String parse(byte[]a){for(int i=0;i+10<a.length;i++)if((a[i]&255)==0xd5&&(a[i+1]&255)==0x4b&&(a[i+2]&255)>=1){int p=i+3;p++;p+=2;p++;if(p>=a.length)continue;int n=a[p++]&255;if(n<4||n>10||p+n>a.length)continue;StringBuilder s=new StringBuilder();for(int k=0;k<n;k++){if(k>0)s.append(':');s.append(String.format(Locale.US,"%02X",a[p+k]&255));}return s.toString();}return null;}void msg(String s){ui.post(()->status.setText(s));}void dmsg(String s){ui.post(()->diag.setText(s));}protected void onDestroy(){try{if(port!=null)port.close();}catch(Exception e){}unregisterReceiver(rx);super.onDestroy();}
}