const levels=[{id:"easy-1",title:"Four quarter notes",bpm:80,beatsPerBar:4,bars:1,difficulty:"Easy",pattern:[0,1,2,3]},{id:"easy-2",title:"Eighth note pairs",bpm:90,beatsPerBar:4,bars:1,difficulty:"Easy",pattern:[0,0.5,1,1.5,2,2.5,3,3.5]},{id:"med-1",title:"Groove Builder",bpm:110,beatsPerBar:4,bars:2,difficulty:"Medium",pattern:[0,0.5,1.5,2,3,4,4.5,5.5,6.5,7]},{id:"hard-1",title:"Syncopation Mix",bpm:132,beatsPerBar:4,bars:2,difficulty:"Hard",pattern:[0,0.75,1.5,2.25,3.5,4,4.5,5.25,6,6.75,7.5]}];
const PERFECT=60,GOOD=120,OKAY=180;
const s={level:null,running:false,start:0,expected:[],judged:new Set(),score:0,hit:0,miss:0,streak:0,best:0,counts:{Perfect:0,Good:0,Okay:0,Miss:0,Extra:0},muted:false,audio:null,nextBeatTime:0,scheduler:null};
const $=i=>document.getElementById(i);
const refs={cards:$("levelCards"),timeline:$("timeline"),playhead:$("playhead"),feedback:$("feedback"),startBtn:$("startBtn"),tapPad:$("tapPad"),countdown:$("countdown")};
const noteType=v=>{const frac=Math.abs(v-Math.floor(v));if(Math.abs(frac-.25)<.01||Math.abs(frac-.75)<.01)return'sixteenth';if(Math.abs(frac-.5)<.01)return'eighth';return'quarter';};
function drawNote(pos,type){const n=document.createElement('div');n.className=`note ${type}`;n.style.left=`${pos}%`;n.innerHTML='<span class="head"></span><span class="stem"></span>'+(type!=='quarter'?'<span class="flag"></span>':'')+(type==='sixteenth'?'<span class="flag2"></span>':'');return n;}
function renderTimeline(level){refs.timeline.innerHTML='';const total=level.beatsPerBar*level.bars;level.pattern.forEach(p=>refs.timeline.appendChild(drawNote(p/total*100,noteType(p))));}
function renderLevels(){refs.cards.innerHTML='';[...levels,...loadCustom()].forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';b.dataset.idx=String(i+1);b.innerHTML=`<strong>${l.title}</strong><div>${l.difficulty} • ${l.bpm} BPM</div><small>PULSATE ✓</small>`;b.onclick=()=>{document.querySelectorAll('.level-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');s.level=l;$("currentLevelTitle").textContent=l.title;$("currentLevelMeta").textContent=`${l.bpm} BPM • ${l.bars} bar(s) • ${l.difficulty}`;refs.startBtn.disabled=false;renderTimeline(l);};refs.cards.appendChild(b);});}
async function ensureAudio(){if(!s.audio){s.audio=new (window.AudioContext||window.webkitAudioContext)();s.master=s.audio.createGain();s.master.gain.value=.85;s.master.connect(s.audio.destination);}if(s.audio.state==='suspended')await s.audio.resume();}
function clickSound(t,strong=false){if(s.muted||!s.audio)return;const o=s.audio.createOscillator(),g=s.audio.createGain();o.type='triangle';o.frequency.setValueAtTime(strong?1760:1180,t);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.09,t+0.003);g.gain.exponentialRampToValueAtTime(0.0001,t+0.05);o.connect(g).connect(s.master);o.start(t);o.stop(t+0.06);}
function startScheduler(level){const spb=60/level.bpm;const beats=level.beatsPerBar*level.bars;s.nextBeatTime=s.audio.currentTime+0.05;let beat=0;clearInterval(s.scheduler);s.scheduler=setInterval(()=>{while(s.nextBeatTime<s.audio.currentTime+0.12 && beat<beats){clickSound(s.nextBeatTime,beat%level.beatsPerBar===0);s.nextBeatTime+=spb;beat++;}},25);}
function stopScheduler(){clearInterval(s.scheduler);s.scheduler=null;}
async function startGame(level){reset();await ensureAudio();await countdown();s.running=true;refs.tapPad.disabled=false;const beatMs=60000/level.bpm,total=level.beatsPerBar*level.bars*beatMs;s.expected=level.pattern.map(p=>p*beatMs);s.start=performance.now();startScheduler(level);requestAnimationFrame(function raf(now){if(!s.running)return;const el=now-s.start;const pct=Math.min(100,el/total*100);refs.playhead.style.left=`${pct}%`;document.getElementById('progress').style.width=`${pct}%`;autoMiss(el);if(el>=total+OKAY){finish();return;}requestAnimationFrame(raf);});}
function judge(t){if(!s.running)return;const elapsed=t-s.start;let idx=-1,d=Infinity;s.expected.forEach((e,i)=>{if(s.judged.has(i))return;const dd=Math.abs(elapsed-e);if(dd<d){d=dd;idx=i;}});if(idx<0){s.counts.Extra++;feedback('Extra tap',0);return;}if(d<=OKAY){s.judged.add(idx);s.hit++;const lbl=d<=PERFECT?'Perfect':d<=GOOD?'Good':'Okay';s.counts[lbl]++;s.streak++;s.best=Math.max(s.best,s.streak);s.score+=lbl==='Perfect'?100:lbl==='Good'?70:40;feedback(lbl,1);}else{s.counts.Extra++;s.miss++;s.streak=0;feedback('Miss (extra)',0);}tapFx();sync();}
function autoMiss(elapsed){s.expected.forEach((e,i)=>{if(!s.judged.has(i)&&elapsed-e>OKAY){s.judged.add(i);s.counts.Miss++;s.miss++;s.streak=0;feedback('Miss',0);sync();}});}
function finish(){s.running=false;refs.tapPad.disabled=true;stopScheduler();const total=s.hit+s.miss;$("finalScore").textContent=s.score;$("finalAccuracy").textContent=total?`${Math.round(s.hit/total*100)}%`:'0%';$("bestStreak").textContent=s.best;$("ratingBreakdown").textContent=`${s.counts.Perfect} / ${s.counts.Good} / ${s.counts.Okay} / ${s.counts.Miss+s.counts.Extra}`;$("resultsPanel").hidden=false;}
function feedback(txt,g){refs.feedback.textContent=txt;refs.feedback.style.color=g?'var(--good)':'var(--bad)';}
function sync(){const total=s.hit+s.miss;$("scoreVal").textContent=s.score;$("streakVal").textContent=s.streak;$("accuracyVal").textContent=total?`${Math.round(s.hit/total*100)}%`:'0%';}
function reset(){Object.assign(s,{running:false,start:0,expected:[],judged:new Set(),score:0,hit:0,miss:0,streak:0,best:0,counts:{Perfect:0,Good:0,Okay:0,Miss:0,Extra:0}});$("resultsPanel").hidden=true;refs.playhead.style.left='0%';document.getElementById('progress').style.width='0%';sync();}
async function countdown(){for(const n of ['3','2','1','Go']){refs.countdown.textContent=n;clickSound(s.audio.currentTime+(n==='Go'?0:0),n==='Go');await new Promise(r=>setTimeout(r,620));}refs.countdown.textContent='';}
function tapFx(){clickSound(s.audio.currentTime,false);}
function loadCustom(){return JSON.parse(localStorage.getItem('rhythmCustomLevels')||'[]');}
function saveCustom(level){const all=loadCustom().filter(l=>l.id!==level.id);all.push(level);localStorage.setItem('rhythmCustomLevels',JSON.stringify(all));}
function buildGrid(){const beats=+$("customBeats").value,bars=+$("customBars").value,res=+$("customResolution").value,total=beats*bars*(res/4),g=$("customGrid");g.innerHTML='';for(let i=0;i<total;i++){const c=document.createElement('button');c.className='grid-cell'+(i%(res/4)===0?' beat':'');c.onclick=()=>{c.classList.toggle('active');preview();};g.appendChild(c);}preview();}
function pattern(){const beats=+$("customBeats").value,bars=+$("customBars").value,res=+$("customResolution").value,step=4/res;return [...$("customGrid").children].flatMap((c,i)=>c.classList.contains('active')?[+(i*step).toFixed(2)]:[]).filter(v=>v<beats*bars);}
function preview(){$("patternPreview").textContent=JSON.stringify(pattern());}
function customLevel(){const bpm=+$("customBpm").value,beats=+$("customBeats").value,bars=+$("customBars").value,p=pattern();if(bpm<40||bpm>220||beats<2||beats>12||bars<1||bars>8||p.length<1){alert('Please enter valid settings and at least one note.');return null;}return{id:`custom-${Date.now()}`,title:$("customName").value||'My rhythm',bpm,beatsPerBar:beats,bars,difficulty:$("customDifficulty").value||'Custom',pattern:p};}
refs.startBtn.onclick=()=>s.level&&startGame(s.level);refs.tapPad.onclick=()=>judge(performance.now());document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();judge(performance.now());}});
$("retryBtn").onclick=()=>s.level&&startGame(s.level);$("muteToggle").onclick=e=>{s.muted=!s.muted;e.target.textContent=s.muted?'🔇':'🔊';};['customBeats','customBars','customResolution'].forEach(id=>$(id).addEventListener('change',buildGrid));
$("playCustomBtn").onclick=()=>{const l=customLevel();if(!l)return;s.level=l;$("currentLevelTitle").textContent=l.title;$("currentLevelMeta").textContent=`${l.bpm} BPM • ${l.bars} bar(s) • ${l.difficulty}`;renderTimeline(l);startGame(l);};
$("saveCustomBtn").onclick=()=>{const l=customLevel();if(!l)return;saveCustom(l);renderLevels();alert('Saved.');};$("loadCustomBtn").onclick=()=>{const all=loadCustom();if(!all.length)return alert('No saved custom levels');const l=all[all.length-1];$("customName").value=l.title;$("customBpm").value=l.bpm;$("customBeats").value=l.beatsPerBar;$("customBars").value=l.bars;$("customDifficulty").value=l.difficulty;$("customResolution").value=16;buildGrid();const set=new Set(l.pattern.map(v=>Math.round(v/.25)));[...$("customGrid").children].forEach((c,i)=>c.classList.toggle('active',set.has(i)));preview();};
$("deleteCustomBtn").onclick=()=>{localStorage.removeItem('rhythmCustomLevels');renderLevels();alert('Deleted saved custom levels.');};$("resetCustomBtn").onclick=()=>{[...$("customGrid").children].forEach(c=>c.classList.remove('active'));preview();};
buildGrid();renderLevels();
